import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
  en: {
    software: "Software",
    documents: "Documents",
    courses: "Courses",
    assets: "Stock Assets",
    share_asset: "Share Asset",
    search_assets_placeholder: "Try 'Modern Template' or 'Abstract Nature'...",
    search: "Search",
    premium_stock_assets: "Premium Stock Assets",
    assets_desc: "Discover 1M+ professional images, templates, and digital assets.",
    share_new_asset: "Share New Asset",
    upload_asset_desc: "Upload your best work for the community to see.",
    asset_title: "Asset Title",
    asset_type: "Asset Type",
    tags_placeholder: "e.g. high-res, flat-design, vibrant",
    upload_asset: "Upload Asset",
    free_download: "FREE DOWNLOAD",
    download_now: "Download Now",
    asset_details: "Asset Details",
    related_tags: "Related Tags",
    forum: "Forum",
    experiences: "Experiences",
    request: "Request",
    more: "More ▾",
    signin: "Sign In",
    signout: "Sign Out",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    language: "Language",
    verify_email: "Verify Your Email",
    verify_desc: "Your account is almost ready! We've sent a verification link to",
    verify_desc2: "Please verify your email to unlock all features.",
    resend: "Resend Verification Email",
    signout_try: "Sign Out & Try Again",
    already_verified: "Already verified?",
    refresh: "Refresh page",
    built_for: "Built for the tech community.",
    home_hero_title: "Master IT With The Community",
    home_hero_desc: "A central hub for developers and IT professionals. Share your experiences, discover short courses, and read extensive tech documents.",
    explore_courses: "Explore Courses",
    read_experiences: "Read Experiences",
    featured_resources: "Featured Tech Resources",
    watch_video: "Watch Video",
    read_story: "Read Story",
    download_pdf: "Download PDF",
    course: "Course",
    experience: "Experience",
    document: "Document",
    short_video_courses: "Short Video Courses",
    courses_subtitle: "Up-skill yourself with bite-sized crash courses from industry leads, hosted lightning-fast on Cloudflare R2.",
    all: "All",
    network: "Network",
    code: "Code",
    computer: "Computer",
    security: "Security",
    cloud: "Cloud",
    office: "Office",
    media: "Media",
    driver: "Driver",
    start_course: "Start Course",
    coming_soon: "Feature coming soon!",
    no_content_found: "No content found for",
    software_repository_title: "Software Repository",
    software_repository_desc: "Browse through our structured repository to find the necessary installers, applications, and tools.",
    search_software: "Search software, tools...",
    windows: "Windows",
    macos: "Mac OS",
    new: "NEW",
    details: "Details",
    no_matches_found: "No matches found",
    search_no_match: "We couldn't find any software matching",
    folder: "Folder",
    repository: "Repository",
    win_repo_desc: "Windows OS structured repository",
    mac_repo_desc: "macOS structured repository",
    back_to: "Back to",
    back_to_folders: "Back to Folders",
    back_to_all: "Back to All",
    printer_driver: "Printer Driver",
    graphic_card: "Graphic Card",
    network_card: "Network Card",
    sound_card: "Sound Card",
    chipset: "Chipset",
    office_2021: "Office 2021",
    office_2019: "Office 2019",
    office_2016: "Office 2016",
    office_2013: "Office 2013",
    office_365: "Office 365",
    apps_in: "Apps in",
    documents_explorer: "Explorer",
    all_documents: "All Documents",
    search_files: "Search files...",
    root: "Root",
    all_languages: "All Languages",
    khmer: "Khmer",
    english: "English",
    name_az: "Name (A-Z)",
    date_newest: "Date (Newest)",
    size_largest: "Size (Largest)",
    type: "Type",
    quick_access: "Quick Access",
    files: "Files",
    view: "View",
    download: "Download",
    downloading: "Downloading...",
    community_forum_title: "Community Q&A Forum",
    community_forum_desc: "Ask questions, get help, and discuss IT topics with the community.",
    loading_posts: "Loading posts...",
    no_posts_yet: "No posts yet. Be the first to ask a question!",
    repost_now: "Repost Now",
    delete_post: "Delete Post",
    replies: "Replies",
    reply: "Reply",
    write_reply: "Write a reply...",
    already_replied: "You have already replied to this post.",
    posting_as: "Posting as",
    ask_question: "Ask a Question",
    question_title: "Question title...",
    question_desc: "Describe your issue or question in detail...",
    post_question: "Post Question",
    posting: "Posting...",
    need_nickname: "You need a nickname to post. Go to Profile → Set Nickname first.",
    request_resource_title: "Request Resource",
    request_resource_desc: "Can't find the software or document you need? Let us know and we'll add it!",
    request_submitted: "Request Submitted!",
    request_submitted_desc: "We will review and add this resource shortly.",
    resource_type: "Resource Type",
    resource_name: "Resource Name",
    additional_details: "Additional Information (Optional)",
    resource_software: "Software / Application",
    resource_document: "Document / Book",
    resource_course: "Course / Tutorial",
    resource_other: "Other",
    submit_request: "Submit Request",
    welcome_back: "Welcome Back",
    create_account: "Create Account",
    reset_password: "Reset Password",
    sign_in_desc: "Sign in to access resources",
    sign_up_desc: "Join the IT community today",
    forgot_desc: "Enter your email to receive a reset link",
    email_address: "Email Address",
    password: "Password",
    remember_me: "Remember me",
    forgot_password_q: "Forgot password?",
    signing_in: "Signing in...",
    or: "OR",
    continue_with_google: "Continue with Google",
    no_account: "Don't have an account?",
    full_name: "Full Name",
    confirm_password: "Confirm Password",
    agree_terms: "I agree to the Terms and Privacy Policy",
    creating_account: "Creating account...",
    have_account: "Already have an account?",
    send_reset_link: "Send Reset Link",
    send_reset_link: "Send Reset Link",
    remembered_password: "Remembered your password?",
    set_nickname: "Set your nickname",
    write_bio: "Write a short bio...",
    add_location: "Add location",
    add_website: "Add website",
    joined: "Joined",
    posts: "Posts",
    downloads: "Downloads",
    activity: "Activity",
    saved: "Saved",
    settings: "Settings",
    account_settings: "Account Settings",
    name: "Name",
    location: "Location",
    language: "Language",
    size: "Size",
    date: "Date",
    actions: "Actions",
    support_us: "Support Us",
    buy_us_coffee: "Buy us a Coffee",
    donate_desc: "Your support helps us maintain the repository",
    other: "Other",
    enter_amount: "Enter amount...",
    expires_in: "Expires in",
    i_have_paid: "I have paid",
    thank_you: "Thank You!",
    thank_you_desc: "Your support helps us keep the project alive. You're awesome!",
    retry: "Retry",
    expired: "Expired",
    scan_bakong: "Scan with any Bakong supported app",
    download_code: "Download Code",
    giveaway: "Giveaway",
    left_count: "Left",
    copy: "Copy",
    copied: "Copied!",
    fully_claimed: "Fully Claimed",
  },
  km: {
    software: "កម្មវិធី",
    documents: "ឯកសារ",
    courses: "វគ្គសិក្សា",
    assets: "ធនធានរូបភាព",
    share_asset: "ចែករំលែកធនធាន",
    search_assets_placeholder: "សាកល្បង 'Modern Template' ឬ 'Abstract Nature'...",
    search: "ស្វែងរក",
    premium_stock_assets: "ធនធានរូបភាព និងពុម្ពគំរូ",
    assets_desc: "ស្វែងរក រូបភាព ពុម្ពគំរូ និងធនធានឌីជីថលអាជីពជាង ១លាន។",
    share_new_asset: "ចែករំលែកធនធានថ្មី",
    upload_asset_desc: "បង្ហោះស្នាដៃល្អបំផុតរបស់អ្នកសម្រាប់សហគមន៍។",
    asset_title: "ចំណងជើង",
    asset_type: "ប្រភេទ",
    tags_placeholder: "ឧទាហរណ៍៖ high-res, flat-design, vibrant",
    upload_asset: "បង្ហោះធនធាន",
    free_download: "ទាញយកដោយឥតគិតថ្លៃ",
    download_now: "ទាញយកឥឡូវនេះ",
    asset_details: "ព័ត៌មានលម្អិត",
    related_tags: "ពាក្យគន្លឹះពាក់ព័ន្ធ",
    forum: "វេទិកាពិភាក្សា",
    experiences: "បទពិសោធន៍",
    request: "ស្នើសុំធនធាន",
    more: "បន្ថែម ▾",
    signin: "ចូលគណនី",
    signout: "ចាកចេញ",
    light_mode: "ទម្រង់ភ្លឺ",
    dark_mode: "ទម្រង់ងងឹត",
    language: "ភាសា",
    verify_email: "បញ្ជាក់អុីមែលរបស់អ្នក",
    verify_desc: "គណនីរបស់អ្នកជិតរួចរាល់ហើយ! យើងបានផ្ញើតំណរភ្ជាប់ទៅកាន់",
    verify_desc2: "សូមធ្វើការបញ្ជាក់អុីមែលរបស់អ្នកដើម្បីប្រើប្រាស់មុខងារទាំងអស់។",
    resend: "ផ្ញើតំណរភ្ជាប់បញ្ជាក់ម្ដងទៀត",
    signout_try: "ចាកចេញ និង ព្យាយាមម្ដងទៀត",
    already_verified: "បានបញ្ជាក់រួចរាល់ហើយមែនទេ?",
    refresh: "ផ្ទុកទំព័រឡើងវិញ",
    built_for: "បង្កើតឡើងសម្រាប់សហគមន៍បច្ចេកវិទ្យា។",
    home_hero_title: "ធ្វើជាម្ចាស់ជាមួយសហគមន៍ IT",
    home_hero_desc: "មជ្ឈមណ្ឌលសម្រាប់អ្នកអភិវឌ្ឍន៍ និងអ្នកជំនាញ IT។ ចែករំលែកបទពិសោធន៍ ស្វែងរកវគ្គសិក្សាខ្លីៗ និងអានឯកសារបច្ចេកវិទ្យា។",
    explore_courses: "ស្វែងរកវគ្គសិក្សា",
    read_experiences: "អានបទពិសោធន៍",
    featured_resources: "ធនធានបច្ចេកវិទ្យាពិសេសៗ",
    watch_video: "មើលវីដេអូ",
    read_story: "អានរឿងរ៉ាវ",
    download_pdf: "ទាញយក PDF",
    course: "វគ្គសិក្សា",
    experience: "បទពិសោធន៍",
    document: "ឯកសារ",
    short_video_courses: "វគ្គសិក្សាវីដេអូខ្លីៗ",
    courses_subtitle: "បង្កើនជំនាញរបស់អ្នកជាមួយនឹងវគ្គសិក្សាខ្នាតតូចពីអ្នកជំនាញក្នុងវិស័យនេះ ដែលត្រូវបានរក្សាទុកយ៉ាងលឿននៅលើ Cloudflare R2។",
    all: "ទាំងអស់",
    network: "បណ្ដាញ",
    code: "កូដ",
    computer: "កុំព្យូទ័រ",
    security: "សន្តិសុខ",
    cloud: "ក្លោដ",
    office: "Office",
    media: "Media",
    driver: "Driver",
    start_course: "ចាប់ផ្តើមរៀន",
    coming_soon: "មុខងារនេះនឹងមកដល់ក្នុងពេលឆាប់ៗនេះ!",
    no_content_found: "មិនមានខ្លឹមសារសម្រាប់",
    software_repository_title: "បណ្ណាល័យកម្មវិធី",
    software_repository_desc: "ស្វែងរកតាមរយៈឃ្លាំងកម្មវិធីរបស់យើង ដើម្បីស្វែងរកកម្មវិធី និងឧបករណ៍ដែលអ្នកត្រូវការ។",
    search_software: "ស្វែងរកកម្មវិធី ឧបករណ៍...",
    windows: "Windows",
    macos: "Mac OS",
    new: "ថ្មី",
    details: "ព័ត៌មានលម្អិត",
    no_matches_found: "រកមិនឃើញ",
    search_no_match: "យើងមិនអាចរកឃើញកម្មវិធីដែលត្រូវនឹង",
    folder: "ថត (Folder)",
    repository: "ឃ្លាំងផ្ទុក",
    win_repo_desc: "ឃ្លាំងកម្មវិធីសម្រាប់ Windows",
    mac_repo_desc: "ឃ្លាំងកម្មវិធីសម្រាប់ macOS",
    back_to: "ត្រឡប់ទៅ",
    back_to_folders: "ត្រឡប់ទៅ Folders ដើម",
    back_to_all: "ត្រឡប់ទៅចំណុចដើម",
    printer_driver: "កម្មវិធីបញ្ជាម៉ាស៊ីនបោះពុម្ព (Printer Driver)",
    graphic_card: "កម្មវិធីបញ្ជាក្រាហ្វិក (Graphic Card)",
    network_card: "កម្មវិធីបញ្ជាបណ្ដាញ (Network Card)",
    sound_card: "កម្មវិធីបញ្ជាសំឡេង (Sound Card)",
    chipset: "Chipset Driver",
    office_2021: "Office 2021",
    office_2019: "Office 2019",
    office_2016: "Office 2016",
    office_2013: "Office 2013",
    office_365: "Office 365",
    apps_in: "កម្មវិធីនៅក្នុង",
    documents_explorer: "ការរុករក",
    all_documents: "ឯកសារទាំងអស់",
    search_files: "ស្វែងរកឯកសារ...",
    root: "Root",
    all_languages: "ភាសាទាំងអស់",
    khmer: "ភាសាខ្មែរ",
    english: "ភាសាអង់គ្លេស",
    name_az: "ឈ្មោះ (A-Z)",
    date_newest: "កាលបរិច្ឆេទ (ថ្មីបំផុត)",
    size_largest: "ទំហំ (ធំបំផុត)",
    type: "ប្រភេទ",
    quick_access: "ការចូលប្រើរហ័ស",
    files: "ឯកសារ",
    view: "មើល",
    download: "ទាញយក",
    downloading: "កំពុងទាញយក...",
    community_forum_title: "វេទិកាពិភាក្សាសហគមន៍",
    community_forum_desc: "សួរចំណោទ ទទួលជំនួយ និងពិភាក្សាអំពីប្រធានបទ IT ជាមួយសហគមន៍។",
    loading_posts: "កំពុងផ្ទុកសំណួរ...",
    no_posts_yet: "មិនទាន់មានសំណួរនៅឡើយទេ។ ក្លាយជាអ្នកដំបូងដែលសួរសំណួរ!",
    repost_now: "បង្ហោះឡើងវិញ",
    delete_post: "លុបសំណួរ",
    replies: "ការឆ្លើយតប",
    reply: "ឆ្លើយតប",
    write_reply: "សរសេរការឆ្លើយតប...",
    already_replied: "អ្នកបានឆ្លើយតបរួចហើយសម្រាប់សំណួរនេះ។",
    posting_as: "បង្ហោះក្នុងនាម",
    ask_question: "សួរសំណួរ",
    question_title: "ចំណងជើងសំណួរ...",
    question_desc: "រៀបរាប់អំពីបញ្ហា ឬសំណួររបស់អ្នកឱ្យបានលម្អិត...",
    post_question: "ផ្ញើសំណួរ",
    posting: "កំពុងផ្ញើ...",
    need_nickname: "អ្នកត្រូវការឈ្មោះហៅក្រៅដើម្បីបង្ហោះ។ សូមទៅកាន់ Profile → កំណត់ឈ្មោះហៅក្រៅជាមុនសិន។",
    request_resource_title: "ស្នើសុំធនធាន",
    request_resource_desc: "រកមិនឃើញកម្មវិធី ឬឯកសារដែលអ្នកត្រូវការមែនទេ? ប្រាប់យើងមក យើងនឹងបន្ថែមវាឱ្យ!",
    request_submitted: "បានផ្ញើការស្នើសុំរួចរាល់!",
    request_submitted_desc: "យើងនឹងពិនិត្យ និងបន្ថែមធនធាននេះក្នុងពេលឆាប់ៗ។",
    resource_type: "ប្រភេទធនធាន",
    resource_name: "ឈ្មោះធនធាន",
    additional_details: "ព័ត៌មានបន្ថែម (តាមចំណង់ចំណូលចិត្ត)",
    resource_software: "កម្មវិធី / Application",
    resource_document: "ឯកសារ / សៀវភៅ",
    resource_course: "វគ្គសិក្សា / ការបង្រៀន",
    resource_other: "ផ្សេងៗ",
    submit_request: "ផ្ញើការស្នើសុំ",
    welcome_back: "សូមស្វាគមន៍មកវិញ",
    create_account: "បង្កើតគណនី",
    reset_password: "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
    sign_in_desc: "ចូលគណនីដើម្បីប្រើប្រាស់ធនធាន",
    sign_up_desc: "ចូលរួមជាមួយសហគមន៍ IT ថ្ងៃនេះ",
    forgot_desc: "បញ្ចូលអុីមែលរបស់អ្នកដើម្បីទទួលបានតំណភ្ជាប់កំណត់ឡើងវិញ",
    email_address: "អាសយដ្ឋានអុីមែល",
    password: "ពាក្យសម្ងាត់",
    remember_me: "ចងចាំខ្ញុំ",
    forgot_password_q: "ភ្លេចពាក្យសម្ងាត់?",
    signing_in: "កំពុងចូល...",
    or: "ឬ",
    continue_with_google: "បន្តជាមួយ Google",
    no_account: "មិនទាន់មានគណនីមែនទេ?",
    full_name: "ឈ្មោះពេញ",
    confirm_password: "បញ្ជាក់ពាក្យសម្ងាត់",
    agree_terms: "ខ្ញុំយល់ព្រមតាមលក្ខខណ្ឌ និងគោលការណ៍ឯកជនភាព",
    creating_account: "កំពុងបង្កើតគណនី...",
    have_account: "មានគណនីរួចហើយមែនទេ?",
    send_reset_link: "ផ្ញើតំណភ្ជាប់កំណត់ឡើងវិញ",
    send_reset_link: "ផ្ញើតំណភ្ជាប់កំណត់ឡើងវិញ",
    remembered_password: "ចាំពាក្យសម្ងាត់របស់អ្នកមែនទេ?",
    set_nickname: "កំណត់ឈ្មោះហៅក្រៅ",
    write_bio: "សរសេរជីវប្រវត្តិខ្លីៗ...",
    add_location: "បន្ថែមទីតាំង",
    add_website: "បន្ថែមគេហទំព័រ",
    joined: "បានចូលរួម",
    posts: "ការបង្ហោះ",
    downloads: "ការទាញយក",
    activity: "សកម្មភាព",
    saved: "បានរក្សាទុក",
    settings: "ការកំណត់",
    account_settings: "ការកំណត់គណនី",
    name: "ឈ្មោះ",
    location: "ទីតាំង",
    language: "ភាសា",
    size: "ទំហំ",
    date: "កាលបរិច្ឆេទ",
    actions: "សកម្មភាព",
    support_us: "គាំទ្រពួកយើង",
    buy_us_coffee: "ទិញកាហ្វេឱ្យពួកយើង",
    donate_desc: "ការគាំទ្ររបស់អ្នកជួយឱ្យយើងអាចបន្តគម្រោងនេះទៅមុខទៀតបាន",
    other: "ផ្សេងៗ",
    enter_amount: "បញ្ចូលទឹកប្រាក់...",
    expires_in: "ផុតកំណត់ក្នុងរយៈពេល",
    i_have_paid: "ខ្ញុំបានបង់ប្រាក់រួចហើយ",
    thank_you: "សូមអរគុណ!",
    thank_you_desc: "ការគាំទ្ររបស់អ្នកជួយឱ្យយើងអាចបន្តគម្រោងនេះទៅមុខទៀតបាន។ អ្នកពិតជាអស្ចារ្យណាស់!",
    retry: "ព្យាយាមម្ដងទៀត",
    expired: "ផុតកំណត់",
    scan_bakong: "ស្កែនជាមួយកម្មវិធីដែលគាំទ្រ Bakong",
    download_code: "ទាញយកកូដ",
    giveaway: "ចែករង្វាន់",
    left_count: "នៅសល់",
    copy: "ចម្លង",
    copied: "បានចម្លង!",
    fully_claimed: "ត្រូវបានបើកអស់ហើយ",
  }

};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
